// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Alexandru Negoita

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// In Docker, dotenv is not needed as env vars are passed directly by docker-compose
try {
  require("dotenv/config");
} catch (e) {
  // dotenv not available in production Docker, env vars come from docker-compose
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
